/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ELineChart {
    }
}
declare global {
    interface HTMLELineChartElement extends Components.ELineChart, HTMLStencilElement {
    }
    var HTMLELineChartElement: {
        prototype: HTMLELineChartElement;
        new (): HTMLELineChartElement;
    };
    interface HTMLElementTagNameMap {
        "e-line-chart": HTMLELineChartElement;
    }
}
declare namespace LocalJSX {
    interface ELineChart {
    }
    interface IntrinsicElements {
        "e-line-chart": ELineChart;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "e-line-chart": LocalJSX.ELineChart & JSXBase.HTMLAttributes<HTMLELineChartElement>;
        }
    }
}
