/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Dimensions, Source } from "./components/e-line-chart/e-line-chart";
import { TitleComponentOption } from "echarts/components";
import { Person } from "./components/hello-stencil/hello-stencil";
export namespace Components {
    interface ELineChart {
        "backgroundColor"?: string;
        "chartTitle"?: string | TitleComponentOption;
        "dimensions": Dimensions;
        "height"?: string | number;
        "source": Source;
        "width"?: string | number;
        "yName"?: string;
        "yNameColor"?: string;
        "yNameLocation"?: 'start' | 'middle' | 'end';
    }
    interface HelloStencil {
        "array": Person[];
        "attrArray": Person[];
        "attrPerson": Person;
        "name": string;
        "person": Person;
    }
}
export interface HelloStencilCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLHelloStencilElement;
}
declare global {
    interface HTMLELineChartElement extends Components.ELineChart, HTMLStencilElement {
    }
    var HTMLELineChartElement: {
        prototype: HTMLELineChartElement;
        new (): HTMLELineChartElement;
    };
    interface HTMLHelloStencilElement extends Components.HelloStencil, HTMLStencilElement {
    }
    var HTMLHelloStencilElement: {
        prototype: HTMLHelloStencilElement;
        new (): HTMLHelloStencilElement;
    };
    interface HTMLElementTagNameMap {
        "e-line-chart": HTMLELineChartElement;
        "hello-stencil": HTMLHelloStencilElement;
    }
}
declare namespace LocalJSX {
    interface ELineChart {
        "backgroundColor"?: string;
        "chartTitle"?: string | TitleComponentOption;
        "dimensions"?: Dimensions;
        "height"?: string | number;
        "source"?: Source;
        "width"?: string | number;
        "yName"?: string;
        "yNameColor"?: string;
        "yNameLocation"?: 'start' | 'middle' | 'end';
    }
    interface HelloStencil {
        "array"?: Person[];
        "attrArray"?: Person[];
        "attrPerson"?: Person;
        "name"?: string;
        "onMy-click"?: (event: HelloStencilCustomEvent<Person>) => void;
        "onMyClick"?: (event: HelloStencilCustomEvent<Person>) => void;
        "onMyclick"?: (event: HelloStencilCustomEvent<Person>) => void;
        "person"?: Person;
    }
    interface IntrinsicElements {
        "e-line-chart": ELineChart;
        "hello-stencil": HelloStencil;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "e-line-chart": LocalJSX.ELineChart & JSXBase.HTMLAttributes<HTMLELineChartElement>;
            "hello-stencil": LocalJSX.HelloStencil & JSXBase.HTMLAttributes<HTMLHelloStencilElement>;
        }
    }
}
