/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Dimensions, Source } from "./components/e-line-chart/e-line-chart";
import { TitleComponentOption } from "echarts/components";
export namespace Components {
    interface ELineChart {
        "backgroundColor"?: string;
        "chartTitle"?: string | TitleComponentOption;
        "dimensions": Dimensions;
        "height"?: string | number;
        "source": Source;
        "width"?: string | number;
        "yName"?: string;
        "yNameColor"?: string;
        "yNameLocation"?: 'start' | 'middle' | 'end';
    }
}
declare global {
    interface HTMLELineChartElement extends Components.ELineChart, HTMLStencilElement {
    }
    var HTMLELineChartElement: {
        prototype: HTMLELineChartElement;
        new (): HTMLELineChartElement;
    };
    interface HTMLElementTagNameMap {
        "e-line-chart": HTMLELineChartElement;
    }
}
declare namespace LocalJSX {
    interface ELineChart {
        "backgroundColor"?: string;
        "chartTitle"?: string | TitleComponentOption;
        "dimensions"?: Dimensions;
        "height"?: string | number;
        "source"?: Source;
        "width"?: string | number;
        "yName"?: string;
        "yNameColor"?: string;
        "yNameLocation"?: 'start' | 'middle' | 'end';
    }
    interface IntrinsicElements {
        "e-line-chart": ELineChart;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "e-line-chart": LocalJSX.ELineChart & JSXBase.HTMLAttributes<HTMLELineChartElement>;
        }
    }
}
